>P1;3vv9
Structure:3vv9:31:A:297:A:: : :
PVWGHTQLNRLSFLETVPVVPLRVSDESSEDRPTWSLPDIENVAITHKKPNGLVDTLAYR
SVRTCRWLFDTFSLYRFG----------------SITESKVISRCLFLETVAGVPGMVGG
MLRHLSSLRYMTRDKGWINTLLVEAENERMHLMTFIELRQPGLPLRVSIIITQAIMYLFL
LVAYVISPRFVHRFVGYLEEEAVITYTGVMRAIDEGRLRPTKN---DVPEVARVYWNLSK
N-ATFRDLINVIRADEAEHRVVNHTFADMHEKRLQNSVNPFVVLKKN-------------
--------
*
>P1;aox-neuro
Sequence:aox-neuro:: : : : : ::
----------LKDFFPAKETAYIRQTPPAWPHHGWTEEEMTSVVPEHRKPETVGDWLAWK
LVRICRWATDIATGIRPEQQVDKHHPTTATSADKPLTEAQWLVRFIFLESIAGVPGMVAG
MLRHLHSLRRLKRDNGWIETLLEESYNERMHLLTFMKMCEPGLLMKTLILGAQGVFFNAM
FLSYLISPKITHRFVGYLEEEAVHTYTRCIREIEEGHLPKWSDEKFEIPEMAVRYWRMPE
GKRTMKDLIHYIRADEAVHRGVNHTLSNLDQKEDPNPFVSDYKEGEGGRRPVNPALKPTG
FERAEVIG
*
